"""Chemical catalog seed data from GLMC 1.0 Operating SOP Appendix A."""

from battery_erp.app.models.enums import ChemicalUnit

CHEMICAL_CATALOG = [
    {
        "name": "Sulfuric Acid",
        "formula": "H2SO4",
        "concentration_pct": 98.0,
        "molecular_weight": 98.08,
        "unit": ChemicalUnit.KG,
        "hazard_class": "Corrosive",
        "min_stock": 5000,
        "max_stock": 15000,
    },
    {
        "name": "Sulfuric Acid (Dilute)",
        "formula": "H2SO4",
        "concentration_pct": 50.0,
        "molecular_weight": 98.08,
        "unit": ChemicalUnit.KG,
        "hazard_class": "Corrosive",
        "min_stock": 0,
        "max_stock": 0,
    },
    {
        "name": "Hydrogen Peroxide",
        "formula": "H2O2",
        "concentration_pct": 34.0,
        "molecular_weight": 34.01,
        "unit": ChemicalUnit.LITRE,
        "hazard_class": "Oxidizer",
        "min_stock": 1000,
        "max_stock": 5000,
    },
    {
        "name": "Sodium Hydroxide",
        "formula": "NaOH",
        "concentration_pct": 25.0,
        "molecular_weight": 40.00,
        "unit": ChemicalUnit.LITRE,
        "hazard_class": "Corrosive",
        "min_stock": 2000,
        "max_stock": 8000,
    },
    {
        "name": "Ammonium Hydroxide",
        "formula": "NH4OH",
        "concentration_pct": 19.0,
        "molecular_weight": 35.05,
        "unit": ChemicalUnit.LITRE,
        "hazard_class": "Corrosive, Toxic gas",
        "min_stock": 3000,
        "max_stock": 10000,
    },
    {
        "name": "Cobalt Sulfate Heptahydrate",
        "formula": "CoSO4*7H2O",
        "concentration_pct": 100.0,
        "molecular_weight": 281.10,
        "unit": ChemicalUnit.KG,
        "hazard_class": "Toxic",
        "min_stock": 200,
        "max_stock": 1000,
    },
    {
        "name": "Manganese Sulfate Monohydrate",
        "formula": "MnSO4*H2O",
        "concentration_pct": 100.0,
        "molecular_weight": 169.02,
        "unit": ChemicalUnit.KG,
        "hazard_class": "Irritant",
        "min_stock": 200,
        "max_stock": 1000,
    },
    {
        "name": "Calcium Hydroxide",
        "formula": "Ca(OH)2",
        "concentration_pct": 100.0,
        "molecular_weight": 74.09,
        "unit": ChemicalUnit.LB,
        "hazard_class": "Irritant",
        "min_stock": 500,
        "max_stock": 2000,
    },
    {
        "name": "Sodium Carbonate (Soda Ash)",
        "formula": "Na2CO3",
        "concentration_pct": 100.0,
        "molecular_weight": 105.99,
        "unit": ChemicalUnit.LB,
        "hazard_class": "Irritant",
        "min_stock": 500,
        "max_stock": 3000,
    },
]
